server:
  port: 8083
spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active:
      - "default"
  application:
    name: coupons
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
      
  endpoints:
    web:
      exposure:
        include: refresh
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
data:
  info: default profile couponservice

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
