#spring:
#  profiles:
#    active: default
#  application:
#    name: productapp
#    
#  datasource:
#    url: jdbc:mysql://localhost:3306/ora123?useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#
#server:
#  port: 9090
#  servlet:
#    context-path: /productapp
#
#
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR
#
#app:
#  info: productapp default profile yaml wala
